
tables_extra = {}

tables_extra["ship_owner"] = ("ship_owner", "Chủ tàu / Công ty quản lý tàu", [
    (1,  "id",               "INT AUTO_INCREMENT",       "NOT NULL", "auto",   "PK", "Khóa chính"),
    (2,  "code",             "VARCHAR(30)",  "NOT NULL", "",       "",   "Mã nội bộ"),
    (3,  "company_name",     "VARCHAR(200)", "NOT NULL", "",       "",   "Tên công ty"),
    (4,  "company_name_en",  "VARCHAR(200)", "NULL",     "",       "",   "Tên tiếng Anh"),
    (5,  "country_id",       "INT",          "NULL",     "",       "FK", "Quốc gia → country.id"),
    (6,  "address",          "TEXT",         "NULL",     "",       "",   "Địa chỉ"),
    (7,  "phone",            "VARCHAR(30)",  "NULL",     "",       "",   "Điện thoại"),
    (8,  "fax",              "VARCHAR(30)",  "NULL",     "",       "",   "Fax"),
    (9,  "email",            "VARCHAR(150)", "NULL",     "",       "",   "Email"),
    (10, "website",          "VARCHAR(200)", "NULL",     "",       "",   "Website"),
    (11, "contact_person",   "VARCHAR(150)", "NULL",     "",       "",   "Người liên lạc chính"),
    (12, "contact_phone",    "VARCHAR(30)",  "NULL",     "",       "",   "Điện thoại người liên lạc"),
    (13, "contact_email",    "VARCHAR(150)", "NULL",     "",       "",   "Email người liên lạc"),
    (14, "tax_id",           "VARCHAR(50)",  "NULL",     "",       "",   "Mã số thuế"),
    (15, "is_active",        "TINYINT(1)",      "NOT NULL", "TRUE",   "",   "Đang hợp tác"),
    (16, "notes",            "TEXT",         "NULL",     "",       "",   "Ghi chú"),
    (17, "created_at",       "DATETIME",  "NOT NULL", "NOW()",  "",   "Thời điểm tạo"),
    (18, "updated_at",       "DATETIME",  "NOT NULL", "NOW()",  "",   "Thời điểm cập nhật"),
    (19, "deleted_at",       "DATETIME",  "NULL",     "",       "",   "Soft delete"),
])

tables_extra["vessel"] = ("vessel", "Tàu biển", [
    (1,  "id",                    "INT AUTO_INCREMENT",       "NOT NULL", "auto",          "PK", "Khóa chính"),
    (2,  "imo_number",            "VARCHAR(10)",  "NULL",     "",              "",   "Số IMO (7 chữ số)"),
    (3,  "mmsi",                  "VARCHAR(10)",  "NULL",     "",              "",   "Số MMSI"),
    (4,  "call_sign",             "VARCHAR(10)",  "NULL",     "",              "",   "Hô hiệu vô tuyến"),
    (5,  "vessel_name",           "VARCHAR(150)", "NOT NULL", "",              "",   "Tên tàu"),
    (6,  "vessel_name_prev",      "VARCHAR(150)", "NULL",     "",              "",   "Tên cũ (nếu đổi tên)"),
    (7,  "vessel_type_id",        "INT",          "NULL",     "",              "FK", "Loại tàu → vessel_type.id"),
    (8,  "flag_country_id",       "INT",          "NULL",     "",              "FK", "Quốc kỳ → country.id"),
    (9,  "port_of_registry_id",   "INT",          "NULL",     "",              "FK", "Cảng đăng ký → port.id"),
    (10, "gross_tonnage",         "NUMERIC(10,2)","NULL",     "",              "",   "Tổng dung tích (GT)"),
    (11, "net_tonnage",           "NUMERIC(10,2)","NULL",     "",              "",   "Dung tích thuần (NT)"),
    (12, "deadweight",            "NUMERIC(10,2)","NULL",     "",              "",   "Trọng tải (DWT, tấn)"),
    (13, "length_overall",        "NUMERIC(8,2)", "NULL",     "",              "",   "Chiều dài tổng thể LOA (m)"),
    (14, "year_built",            "SMALLINT",     "NULL",     "",              "",   "Năm đóng tàu"),
    (15, "classification_society","VARCHAR(50)",  "NULL",     "",              "",   "Đăng kiểm (DNV, Lloyd's, BV...)"),
    (16, "ship_owner_id",         "INT",          "NULL",     "",              "FK", "Chủ tàu → ship_owner.id"),
    (17, "technical_manager",     "VARCHAR(200)", "NULL",     "",              "",   "Công ty quản lý kỹ thuật"),
    (18, "commercial_manager",    "VARCHAR(200)", "NULL",     "",              "",   "Công ty quản lý thương mại"),
    (19, "status",                "VARCHAR(30)",  "NOT NULL", "'IN_SERVICE'",  "",   "Trạng thái: IN_SERVICE / LAID_UP / SCRAPPED / SOLD"),
    (20, "notes",                 "TEXT",         "NULL",     "",              "",   "Ghi chú"),
    (21, "created_at",            "DATETIME",  "NOT NULL", "NOW()",         "",   "Thời điểm tạo"),
    (22, "updated_at",            "DATETIME",  "NOT NULL", "NOW()",         "",   "Thời điểm cập nhật"),
    (23, "deleted_at",            "DATETIME",  "NULL",     "",              "",   "Soft delete"),
])

tables_extra["vessel_certificate_requirement"] = ("vessel_certificate_requirement", "Ma trận chứng chỉ yêu cầu theo tàu/chức danh (nguồn: STR-05-06)", [
    (1,  "id",                  "INT AUTO_INCREMENT",      "NOT NULL", "auto",  "PK", "Khóa chính"),
    (2,  "vessel_id",           "INT",         "NOT NULL", "",      "FK", "Tàu → vessel.id"),
    (3,  "rank_id",             "INT",         "NOT NULL", "",      "FK", "Chức danh → rank.id"),
    (4,  "certificate_type_id", "INT",         "NOT NULL", "",      "FK", "Loại chứng chỉ → certificate_type.id"),
    (5,  "is_mandatory",        "TINYINT(1)",     "NOT NULL", "TRUE",  "",   "Bắt buộc hay không"),
    (6,  "notes",               "TEXT",        "NULL",     "",      "",   "Ghi chú"),
    (7,  "created_at",          "DATETIME", "NOT NULL", "NOW()", "",   "Thời điểm tạo"),
])

tables_extra["manning_agent"] = ("manning_agent", "Công ty môi giới / cung ứng thuyền viên", [
    (1,  "id",               "INT AUTO_INCREMENT",       "NOT NULL", "auto",  "PK", "Khóa chính"),
    (2,  "code",             "VARCHAR(30)",  "NOT NULL", "",      "",   "Mã nội bộ"),
    (3,  "company_name",     "VARCHAR(200)", "NOT NULL", "",      "",   "Tên công ty"),
    (4,  "company_name_en",  "VARCHAR(200)", "NULL",     "",      "",   "Tên tiếng Anh"),
    (5,  "country_id",       "INT",          "NULL",     "",      "FK", "Quốc gia → country.id"),
    (6,  "license_number",   "VARCHAR(50)",  "NULL",     "",      "",   "Số giấy phép XKLĐ"),
    (7,  "license_expiry",   "DATE",         "NULL",     "",      "",   "Ngày hết hạn giấy phép"),
    (8,  "licensed_by",      "VARCHAR(200)", "NULL",     "",      "",   "Cơ quan cấp phép (Cục QLLĐNN)"),
    (9,  "address",          "TEXT",         "NULL",     "",      "",   "Địa chỉ"),
    (10, "phone",            "VARCHAR(30)",  "NULL",     "",      "",   "Điện thoại"),
    (11, "email",            "VARCHAR(150)", "NULL",     "",      "",   "Email"),
    (12, "contact_person",   "VARCHAR(150)", "NULL",     "",      "",   "Người liên lạc"),
    (13, "contact_phone",    "VARCHAR(30)",  "NULL",     "",      "",   "Điện thoại người liên lạc"),
    (14, "service_fee_usd",  "NUMERIC(10,2)","NULL",     "",      "",   "Phí dịch vụ (USD)"),
    (15, "is_active",        "TINYINT(1)",      "NOT NULL", "TRUE",  "",   "Đang hoạt động"),
    (16, "notes",            "TEXT",         "NULL",     "",      "",   "Ghi chú"),
    (17, "created_at",       "DATETIME",  "NOT NULL", "NOW()", "",   "Thời điểm tạo"),
    (18, "updated_at",       "DATETIME",  "NOT NULL", "NOW()", "",   "Thời điểm cập nhật"),
    (19, "deleted_at",       "DATETIME",  "NULL",     "",      "",   "Soft delete"),
])

tables_extra["employment_contract"] = ("employment_contract", "Hợp đồng lao động hàng hải (nguồn: HD-Hong.xlsx)", [
    (1,  "id",                   "INT AUTO_INCREMENT",        "NOT NULL", "auto",       "PK", "Khóa chính"),
    (2,  "contract_number",      "VARCHAR(50)",   "NOT NULL", "",           "",   "Số hợp đồng"),
    (3,  "seafarer_id",          "INT",           "NOT NULL", "",           "FK", "Thuyền viên → seafarer.id"),
    (4,  "vessel_id",            "INT",           "NOT NULL", "",           "FK", "Tàu → vessel.id"),
    (5,  "ship_owner_id",        "INT",           "NOT NULL", "",           "FK", "Chủ tàu → ship_owner.id"),
    (6,  "manning_agent_id",     "INT",           "NULL",     "",           "FK", "Môi giới → manning_agent.id"),
    (7,  "contract_type_id",     "INT",           "NULL",     "",           "FK", "Loại hợp đồng → contract_type.id"),
    (8,  "rank_id",              "INT",           "NOT NULL", "",           "FK", "Chức danh theo HĐ → rank.id"),
    (9,  "sign_date",            "DATE",          "NOT NULL", "",           "",   "Ngày ký hợp đồng"),
    (10, "start_date",           "DATE",          "NOT NULL", "",           "",   "Ngày lên tàu (sign-on)"),
    (11, "end_date",             "DATE",          "NULL",     "",           "",   "Ngày dự kiến kết thúc"),
    (12, "actual_end_date",      "DATE",          "NULL",     "",           "",   "Ngày thực tế kết thúc (sign-off)"),
    (13, "duration_months",      "SMALLINT",      "NULL",     "",           "",   "Thời hạn hợp đồng (tháng)"),
    (14, "sign_on_port_id",      "INT",           "NULL",     "",           "FK", "Cảng lên tàu → port.id"),
    (15, "sign_off_port_id",     "INT",           "NULL",     "",           "FK", "Cảng xuống tàu → port.id"),
    (16, "basic_wage_usd",       "NUMERIC(10,2)", "NOT NULL", "",           "",   "Lương cơ bản (USD/tháng)"),
    (17, "overtime_rate_usd",    "NUMERIC(8,2)",  "NULL",     "",           "",   "Phụ cấp OT (USD/giờ)"),
    (18, "leave_pay_usd",        "NUMERIC(10,2)", "NULL",     "",           "",   "Phụ cấp nghỉ phép (USD)"),
    (19, "subsistence_usd",      "NUMERIC(8,2)",  "NULL",     "",           "",   "Phụ cấp ăn ở (USD)"),
    (20, "total_monthly_usd",    "NUMERIC(10,2)", "NULL",     "",           "",   "Tổng lương tháng (USD)"),
    (21, "p_and_i_club",         "VARCHAR(100)",  "NULL",     "",           "",   "P&I Club bảo hiểm"),
    (22, "insurance_policy_number","VARCHAR(50)", "NULL",     "",           "",   "Số hợp đồng bảo hiểm"),
    (23, "life_insurance_usd",   "NUMERIC(10,2)", "NULL",     "",           "",   "Bảo hiểm nhân thọ (USD)"),
    (24, "agency_fee_usd",       "NUMERIC(10,2)", "NULL",     "",           "",   "Phí môi giới (USD)"),
    (25, "visa_fee_usd",         "NUMERIC(8,2)",  "NULL",     "",           "",   "Phí visa (USD)"),
    (26, "medical_fee_usd",      "NUMERIC(8,2)",  "NULL",     "",           "",   "Phí khám sức khỏe (USD)"),
    (27, "training_fee_usd",     "NUMERIC(8,2)",  "NULL",     "",           "",   "Phí đào tạo (USD)"),
    (28, "total_cost_usd",       "NUMERIC(10,2)", "NULL",     "",           "",   "Tổng chi phí thuyền viên (USD)"),
    (29, "status",               "VARCHAR(30)",   "NOT NULL", "'DRAFT'",    "",   "Trạng thái: DRAFT/SIGNED/ACTIVE/COMPLETED/TERMINATED/CANCELLED"),
    (30, "termination_reason",   "TEXT",          "NULL",     "",           "",   "Lý do chấm dứt hợp đồng"),
    (31, "notes",                "TEXT",          "NULL",     "",           "",   "Ghi chú"),
    (32, "document_url",         "TEXT",          "NULL",     "",           "",   "File hợp đồng scan"),
    (33, "created_at",           "DATETIME",   "NOT NULL", "NOW()",      "",   "Thời điểm tạo"),
    (34, "updated_at",           "DATETIME",   "NOT NULL", "NOW()",      "",   "Thời điểm cập nhật"),
    (35, "deleted_at",           "DATETIME",   "NULL",     "",           "",   "Soft delete"),
])

tables_extra["contract_payroll"] = ("contract_payroll", "Bảng lương chi tiết theo tháng", [
    (1,  "id",                      "INT AUTO_INCREMENT",        "NOT NULL", "auto",   "PK", "Khóa chính"),
    (2,  "contract_id",             "INT",           "NOT NULL", "",       "FK", "Hợp đồng → employment_contract.id"),
    (3,  "pay_period_year",         "SMALLINT",      "NOT NULL", "",       "",   "Năm thanh toán"),
    (4,  "pay_period_month",        "SMALLINT",      "NOT NULL", "",       "",   "Tháng thanh toán (1-12)"),
    (5,  "basic_wage_usd",          "NUMERIC(10,2)", "NOT NULL", "",       "",   "Lương cơ bản tháng này (USD)"),
    (6,  "overtime_hours",          "NUMERIC(6,2)",  "NULL",     "",       "",   "Số giờ OT"),
    (7,  "overtime_amount_usd",     "NUMERIC(10,2)", "NULL",     "",       "",   "Tiền OT (USD)"),
    (8,  "bonus_usd",               "NUMERIC(10,2)", "NULL",     "",       "",   "Thưởng (USD)"),
    (9,  "gross_usd",               "NUMERIC(10,2)", "NOT NULL", "",       "",   "Tổng thu nhập trước khấu trừ (USD)"),
    (10, "advance_deduction_usd",   "NUMERIC(10,2)", "NULL",     "",       "",   "Khấu trừ tạm ứng (USD)"),
    (11, "insurance_deduction_usd", "NUMERIC(10,2)", "NULL",     "",       "",   "Khấu trừ bảo hiểm (USD)"),
    (12, "net_usd",                 "NUMERIC(10,2)", "NOT NULL", "",       "",   "Thực lĩnh (USD)"),
    (13, "payment_date",            "DATE",          "NULL",     "",       "",   "Ngày thanh toán"),
    (14, "payment_method",          "VARCHAR(30)",   "NULL",     "",       "",   "Hình thức: BANK_TRANSFER / CASH"),
    (15, "is_paid",                 "TINYINT(1)",       "NOT NULL", "FALSE",  "",   "Đã thanh toán chưa"),
    (16, "notes",                   "TEXT",          "NULL",     "",       "",   "Ghi chú"),
    (17, "created_at",              "DATETIME",   "NOT NULL", "NOW()",  "",   "Thời điểm tạo"),
])

tables_extra["training_center"] = ("training_center", "Trung tâm đào tạo thuyền viên", [
    (1,  "id",              "INT AUTO_INCREMENT",       "NOT NULL", "auto",  "PK", "Khóa chính"),
    (2,  "code",            "VARCHAR(30)",  "NOT NULL", "",      "",   "Mã trung tâm (IMSCO, VIMARU...)"),
    (3,  "name_vi",         "VARCHAR(200)", "NOT NULL", "",      "",   "Tên tiếng Việt"),
    (4,  "name_en",         "VARCHAR(200)", "NULL",     "",      "",   "Tên tiếng Anh"),
    (5,  "country_id",      "INT",          "NULL",     "",      "FK", "Quốc gia → country.id"),
    (6,  "license_number",  "VARCHAR(50)",  "NULL",     "",      "",   "Số giấy phép đào tạo"),
    (7,  "license_expiry",  "DATE",         "NULL",     "",      "",   "Ngày hết hạn giấy phép"),
    (8,  "accredited_by",   "VARCHAR(200)", "NULL",     "",      "",   "Cơ quan công nhận (VINAMARINE, IMO...)"),
    (9,  "address",         "TEXT",         "NULL",     "",      "",   "Địa chỉ"),
    (10, "phone",           "VARCHAR(30)",  "NULL",     "",      "",   "Điện thoại"),
    (11, "email",           "VARCHAR(150)", "NULL",     "",      "",   "Email"),
    (12, "contact_person",  "VARCHAR(150)", "NULL",     "",      "",   "Người liên lạc"),
    (13, "is_active",       "TINYINT(1)",      "NOT NULL", "TRUE",  "",   "Đang hoạt động"),
    (14, "notes",           "TEXT",         "NULL",     "",      "",   "Ghi chú"),
    (15, "created_at",      "DATETIME",  "NOT NULL", "NOW()", "",   "Thời điểm tạo"),
    (16, "updated_at",      "DATETIME",  "NOT NULL", "NOW()", "",   "Thời điểm cập nhật"),
])

tables_extra["training_course"] = ("training_course", "Khóa đào tạo cụ thể (một lần mở lớp)", [
    (1,  "id",                 "INT AUTO_INCREMENT",       "NOT NULL", "auto",       "PK", "Khóa chính"),
    (2,  "course_code",        "VARCHAR(50)",  "NOT NULL", "",           "",   "Mã khóa học (ESCO-2024-K6...)"),
    (3,  "course_type_id",     "INT",          "NOT NULL", "",           "FK", "Loại khóa học → course_type.id"),
    (4,  "training_center_id", "INT",          "NOT NULL", "",           "FK", "Trung tâm đào tạo → training_center.id"),
    (5,  "name",               "VARCHAR(200)", "NOT NULL", "",           "",   "Tên khóa học"),
    (6,  "start_date",         "DATE",         "NOT NULL", "",           "",   "Ngày khai giảng"),
    (7,  "end_date",           "DATE",         "NULL",     "",           "",   "Ngày bế giảng"),
    (8,  "location",           "VARCHAR(200)", "NULL",     "",           "",   "Địa điểm tổ chức"),
    (9,  "max_students",       "SMALLINT",     "NULL",     "",           "",   "Sĩ số tối đa"),
    (10, "fee_vnd",            "NUMERIC(12,2)","NULL",     "",           "",   "Học phí (VNĐ)"),
    (11, "fee_usd",            "NUMERIC(10,2)","NULL",     "",           "",   "Học phí (USD)"),
    (12, "instructor",         "VARCHAR(200)", "NULL",     "",           "",   "Giảng viên phụ trách"),
    (13, "status",             "VARCHAR(20)",  "NOT NULL", "'PLANNED'",  "",   "Trạng thái: PLANNED/ONGOING/COMPLETED/CANCELLED"),
    (14, "notes",              "TEXT",         "NULL",     "",           "",   "Ghi chú"),
    (15, "created_at",         "DATETIME",  "NOT NULL", "NOW()",      "",   "Thời điểm tạo"),
    (16, "updated_at",         "DATETIME",  "NOT NULL", "NOW()",      "",   "Thời điểm cập nhật"),
])

tables_extra["training_enrollment"] = ("training_enrollment", "Đăng ký học + kết quả tổng hợp (nguồn: Tong hop danh gia hoc vien.xlsx)", [
    (1,  "id",                  "INT AUTO_INCREMENT",       "NOT NULL", "auto",       "PK", "Khóa chính"),
    (2,  "course_id",           "INT",          "NOT NULL", "",           "FK", "Khóa học → training_course.id"),
    (3,  "seafarer_id",         "INT",          "NOT NULL", "",           "FK", "Thuyền viên → seafarer.id"),
    (4,  "enrollment_date",     "DATE",         "NOT NULL", "",           "",   "Ngày đăng ký"),
    (5,  "rank_at_enrollment",  "INT",          "NULL",     "",           "FK", "Chức danh khi học → rank.id"),
    (6,  "attendance_score",    "NUMERIC(5,2)", "NULL",     "",           "",   "Điểm chuyên cần (vd: 25/25)"),
    (7,  "attendance_max",      "SMALLINT",     "NULL",     "25",         "",   "Điểm chuyên cần tối đa"),
    (8,  "process_score",       "NUMERIC(5,2)", "NULL",     "",           "",   "Điểm đánh giá quá trình học"),
    (9,  "interview_score",     "NUMERIC(5,2)", "NULL",     "",           "",   "Điểm phỏng vấn tổng hợp"),
    (10, "total_score",         "NUMERIC(5,2)", "NULL",     "",           "",   "Tổng điểm"),
    (11, "grade",               "VARCHAR(5)",   "NULL",     "",           "",   "Xếp loại: A+ / A / B+ / B / C / D"),
    (12, "result",              "VARCHAR(20)",  "NULL",     "",           "",   "Kết quả: PASS / FAIL / ABSENT / WITHDRAWN"),
    (13, "certificate_issued",  "TINYINT(1)",      "NOT NULL", "FALSE",      "",   "Đã cấp chứng chỉ chưa"),
    (14, "certificate_id",      "INT",          "NULL",     "",           "FK", "Chứng chỉ được cấp → seafarer_certificate.id"),
    (15, "absence_reason",      "TEXT",         "NULL",     "",           "",   "Lý do vắng mặt / rút lui"),
    (16, "notes",               "TEXT",         "NULL",     "",           "",   "Ghi chú (Phiếu KQ...)"),
    (17, "created_at",          "DATETIME",  "NOT NULL", "NOW()",      "",   "Thời điểm tạo"),
    (18, "updated_at",          "DATETIME",  "NOT NULL", "NOW()",      "",   "Thời điểm cập nhật"),
])

tables_extra["enrollment_score"] = ("enrollment_score", "Điểm chi tiết từng tiêu chí đánh giá (7 tiêu chí phỏng vấn)", [
    (1,  "id",             "INT AUTO_INCREMENT",       "NOT NULL", "auto",  "PK", "Khóa chính"),
    (2,  "enrollment_id",  "INT",          "NOT NULL", "",      "FK", "Đăng ký học → training_enrollment.id"),
    (3,  "criteria_code",  "VARCHAR(50)",  "NOT NULL", "",      "",   "Mã tiêu chí: LISTENING/SPEAKING/COMMUNICATION/SELF_INTRO/RESPONSIBILITY/EMERGENCY/OTHER"),
    (4,  "criteria_name",  "VARCHAR(150)", "NOT NULL", "",      "",   "Tên tiêu chí (Listening skill, Speaking skill...)"),
    (5,  "score",          "NUMERIC(5,2)", "NULL",     "",      "",   "Điểm số"),
    (6,  "max_score",      "NUMERIC(5,2)", "NULL",     "",      "",   "Điểm tối đa"),
    (7,  "grade",          "VARCHAR(5)",   "NULL",     "",      "",   "Xếp loại: A / B / C / D"),
    (8,  "notes",          "TEXT",         "NULL",     "",      "",   "Ghi chú"),
    (9,  "created_at",     "DATETIME",  "NOT NULL", "NOW()", "",   "Thời điểm tạo"),
])
