const authRoutes = require('./auth.routes')
const seafarerRoutes = require('./seafarer.routes')
const { seafarerContactRoutes } = require('./seafarer.routes')
const importRoutes = require('./import.routes')
const lookupRoutes = require('./lookup.routes')
const certificateRoutes = require('./certificate.routes')
const employmentContractRoutes = require('./employment_contract.routes')
const messagingRoutes = require('./messaging.routes')
const masterDataRoutes = require('./master_data.routes')
const usersRoutes = require('./users')
const { deploymentRoutes, deploymentCRUDRoutes } = require('./deployment.routes')
const formTemplateRoutes = require('./form_template.routes')
const vesselRoutes = require('./vessel.routes')
const partnerRoutes = require('./partner.routes')
const jobRoutes = require('./job.routes')
const migrationRoutes = require('../migration.routes')
const seafarerCallRoutes = require('./seafarer_call.routes')
const seafarerPortalRoutes = require('./seafarer_portal.routes')
const salaryRoutes = require('./salary.routes')
const revenueRoutes = require('./revenue.routes')
const pdfScanRoutes = require('./pdf_scan.routes')
const seamanBookRoutes = require('./seaman_book.routes')

async function v1Routes(fastify) {
  fastify.register(authRoutes, { prefix: '/auth' })
  fastify.register(seafarerRoutes, { prefix: '/seafarers' })
  fastify.register(seafarerContactRoutes, { prefix: '/seafarers/:seafarerId/contacts' })
  fastify.register(seafarerCallRoutes, { prefix: '/seafarers/:seafarerId/calls' })
  fastify.register(importRoutes, { prefix: '/import' })
  fastify.register(lookupRoutes, { prefix: '/lookup' })
  fastify.register(certificateRoutes, { prefix: '/seafarers/:seafarerId/certificates' })
  fastify.register(employmentContractRoutes, { prefix: '/employment-contracts' })
  fastify.register(messagingRoutes, { prefix: '/messages' })
  fastify.register(masterDataRoutes, { prefix: '/admin/master' })
  fastify.register(usersRoutes, { prefix: '/users' })
  fastify.register(deploymentRoutes, { prefix: '/seafarers/:seafarerId/deployments' })
  fastify.register(deploymentCRUDRoutes, { prefix: '/deployments' })
  fastify.register(formTemplateRoutes, { prefix: '/forms' })
  fastify.register(vesselRoutes, { prefix: '/vessels' })
  fastify.register(partnerRoutes, { prefix: '/partners' })
  fastify.register(partnerRoutes, { prefix: '/ship-owners' })
  fastify.register(jobRoutes, { prefix: '/jobs' })
  fastify.register(seafarerPortalRoutes, { prefix: '/portal/seafarer' })
  fastify.register(salaryRoutes, { prefix: '/salary' })
  fastify.register(revenueRoutes, { prefix: '/revenue' })
  fastify.register(migrationRoutes, { prefix: '/migration' })
  fastify.register(pdfScanRoutes, { prefix: '/seafarers' })
  fastify.register(seamanBookRoutes)
}

module.exports = v1Routes
