const authRoutes = require('./auth.routes')
const seafarerRoutes = require('./seafarer.routes')
const { seafarerContactRoutes } = require('./seafarer.routes')
const importRoutes = require('./import.routes')
const lookupRoutes = require('./lookup.routes')
const trainingCenterRoutes = require('./training_center.routes')
const trainingCourseRoutes = require('./training_course.routes')
const enrollmentRoutes = require('./enrollment.routes')
const certificateRoutes = require('./certificate.routes')
const employmentContractRoutes = require('./employment_contract.routes')
const seafarerPortalRoutes = require('./seafarer_portal.routes')
const messagingRoutes = require('./messaging.routes')
const qrEnrollmentRoutes = require('./qr_enrollment.routes')
const masterDataRoutes = require('./master_data.routes')
const fleetRoutes = require('./fleet.routes')
const usersRoutes = require('./users')
const notificationRoutes = require('./notification.routes')
const waitlistRoutes = require('./waitlist.routes')

async function v1Routes(fastify) {
  fastify.register(authRoutes, { prefix: '/auth' })
  fastify.register(seafarerRoutes, { prefix: '/seafarers' })
  fastify.register(seafarerContactRoutes, { prefix: '/seafarers/:seafarerId/contacts' })
  fastify.register(importRoutes, { prefix: '/import' })
  fastify.register(lookupRoutes, { prefix: '/lookup' })
  fastify.register(trainingCenterRoutes, { prefix: '/training-centers' })
  fastify.register(trainingCourseRoutes, { prefix: '/training-courses' })
  fastify.register(enrollmentRoutes, { prefix: '/enrollments' })
  fastify.register(certificateRoutes, { prefix: '/seafarers/:seafarerId/certificates' })
  fastify.register(employmentContractRoutes, { prefix: '/employment-contracts' })
  fastify.register(seafarerPortalRoutes, { prefix: '/portal/seafarer' })
  fastify.register(messagingRoutes, { prefix: '/messages' })
  fastify.register(qrEnrollmentRoutes, { prefix: '/qr-enrollment' })
  fastify.register(masterDataRoutes, { prefix: '/admin/master' })
  fastify.register(fleetRoutes, { prefix: '/admin/master' })
  fastify.register(usersRoutes, { prefix: '/users' })
  fastify.register(notificationRoutes, { prefix: '/notifications' })
  fastify.register(waitlistRoutes, { prefix: '/waitlist' })
}

module.exports = v1Routes
