
// Giấy mẫu (giả) cho test màn duyệt.
// [key, nhãn, nhãn tiếng Anh, chữ trên giấy, giá trị AI đề xuất, trạng thái, 'half' nếu nửa dòng]
const f = (key, label, english, raw, value, state, width) => ({ key, label, english, raw, value, state, half: width === 'half', note: null })

export const DEMO_DOCS = [
  {
    key: 'so-23',
    label: 'Sổ thuyền viên · Trang thông tin',
    file: 'so-thuyen-vien-trang-2-3.jpg',
    page: 'Trang 2–3',
    title: ['SỔ THUYỀN VIÊN', "Seaman's book"],
    photo: true,
    stamps: ['CHI CỤC TRƯỞNG'],
    fields: [
      f('no', 'Số', 'No.', 'VN000123-01', 'VN000123-01', 'ACCEPTED'),
      f('name', 'Họ và tên thuyền viên', 'Full name', 'TRẦN MINH KHÔI', 'Trần Minh Khôi', 'ACCEPTED'),
      f('sex', 'Giới tính', 'Sex', 'Nam / Male', 'Nam', 'ACCEPTED', 'half'),
      f('dob', 'Ngày sinh', 'Date of birth', '13.03.1990', '13/03/1990', 'ACCEPTED', 'half'),
      f('pob', 'Nơi sinh', 'Place of birth', 'Hải Dương', 'Hải Dương', 'ACCEPTED'),
      f('nat', 'Quốc tịch', 'Nationality', 'VIỆT NAM', 'Việt Nam', 'ACCEPTED'),
      f('id', 'Số GCMND hoặc hộ chiếu', 'ID card No or passport', '000000123', '000000123', 'PROPOSED'),
      f('issued', 'Nơi cấp, ngày cấp', 'Place, date', 'Hải Phòng, 02 . 02 . 2016', 'Hải Phòng · 02/02/2016', 'ACCEPTED'),
    ],
  },
  {
    key: 'so-45',
    label: 'Sổ thuyền viên · Bố trí chức danh',
    file: 'so-thuyen-vien-trang-4-5.jpg',
    page: 'Trang 4–5',
    title: ['BỐ TRÍ CHỨC DANH', 'Duties Arrangement'],
    stamps: ['CHỦ TÀU · Shipowner', 'THUYỀN TRƯỞNG · Master'],
    fields: [
      f('ship', 'Tên tàu', "Ship's name", 'HALONG SPIRIT', 'MV Halong Spirit', 'ACCEPTED'),
      { ...f('type', 'Loại tàu', 'Type of ship', '', '', 'UNKNOWN', 'half'), note: 'Ô Loại tàu trên sổ để trống.' },
      f('flag', 'Quốc tịch', 'Nationality', 'VN', 'Việt Nam', 'ACCEPTED', 'half'),
      f('gt', 'Tổng dung tích', 'Gross tonnage', '300', '300 GT', 'PROPOSED'),
      f('kw', 'Tổng công suất máy chính', "Main engine's power", '700', '700 kW', 'PROPOSED'),
      f('owner', 'Chủ tàu', 'Shipowner', 'CHỦ TÀU DEMO A', 'Chủ tàu Demo A', 'PROPOSED'),
      f('rank', 'Chức danh', 'Capacity', 'Thợ máy', 'Thợ máy (Motorman)', 'PROPOSED', 'half'),
      f('coc', 'Số GCNKNCM', 'No. of COC', 'A00123.OSE', 'A00123.OSE', 'ACCEPTED', 'half'),
      f('assign', 'Ngày chủ tàu bố trí chức danh', 'Date of embarkation', '04 . 1 . 2016', '04/01/2016', 'ACCEPTED'),
      f('on', 'Tên cảng, ngày xuống tàu', 'Port, date of embarkation', 'HP  04 . 1 . 2016', 'Hải Phòng · 04/01/2016', 'ACCEPTED'),
      { ...f('off', 'Tên cảng, ngày rời tàu', 'Port, date of disembarkation', '14 . 7 . 2016', '14/07/2016', 'DATE_AMBIGUOUS'), note: 'Ngày viết tay, AI chưa chắc tháng 7 hay tháng 1. Tên cảng để trống trên sổ.' },
    ],
  },
  {
    key: 'coc',
    label: 'Chứng chỉ huấn luyện',
    file: 'anh-chung-chi-pccc.jpg',
    page: '1 trang',
    title: ['GIẤY CHỨNG NHẬN HUẤN LUYỆN NGHIỆP VỤ CHUYÊN MÔN', 'Certificate of proficiency'],
    photo: true,
    stamps: ['HIỆU TRƯỞNG · The Rector'],
    fields: [
      f('school', 'Nơi cấp', 'Issued by', 'TRƯỜNG HUẤN LUYỆN DEMO', 'Trường Huấn luyện Demo', 'PROPOSED'),
      f('name', 'Chứng nhận', 'Certifies that', 'TRẦN MINH KHÔI', 'Trần Minh Khôi', 'ACCEPTED'),
      f('dob', 'Sinh ngày', 'Date of birth', '13-03-1990', '13/03/1990', 'ACCEPTED', 'half'),
      f('nat', 'Quốc tịch', 'Nationality', 'VIỆT NAM', 'Việt Nam', 'ACCEPTED', 'half'),
      f('course', 'Khoá huấn luyện', 'Training course', 'ADVANCED FIRE FIGHTING', 'Advanced Fire Fighting', 'PROPOSED'),
      f('reg', 'Theo quy tắc', 'Under Reg.', 'VI/3', 'STCW VI/3', 'ACCEPTED'),
      f('no', 'Giấy chứng nhận số', 'Certificate No', 'A0003.AF/DEMO', 'A0003.AF/DEMO', 'PROPOSED', 'half'),
      f('issuedOn', 'Cấp ngày', 'Issued on', '02-07-2025', '02/07/2025', 'PROPOSED', 'half'),
      f('valid', 'Có giá trị đến', 'Valid until', '02-07-2030', '02/07/2030', 'PROPOSED'),
    ],
  },
  {
    key: 'vac',
    label: 'Giấy tiêm chủng quốc tế',
    file: 'giay-tiem-chung.jpg',
    page: '1 trang',
    title: ['GIẤY CHỨNG NHẬN TIÊM CHỦNG QUỐC TẾ', 'International certificate of vaccination'],
    stamps: ['DẤU KIỂM DỊCH Y TẾ'],
    fields: [
      f('name', 'Chứng nhận (tên)', 'This is to certify that', 'TRAN MINH KHOI', 'Trần Minh Khôi', 'ACCEPTED'),
      f('yob', 'Năm sinh', 'Date of birth', '1990', '1990', 'ACCEPTED', 'half'),
      f('sex', 'Giới tính', 'Sex', 'M', 'Nam', 'ACCEPTED', 'half'),
      f('disease', 'Bệnh', 'Against', 'YELLOW FEVER', 'Sốt vàng', 'ACCEPTED'),
      f('vaccine', 'Nhà sản xuất, số lô', 'Manufacturer, batch no.', 'DEMO PHARMA · L 0000', 'Demo Pharma · L 0000', 'PROPOSED'),
      f('from', 'Hiệu lực từ', 'Valid from', '01/8/2016', '01/08/2016', 'ACCEPTED', 'half'),
      f('to', 'Đến', 'Until', '01/8/2026', '01/08/2026', 'PROPOSED', 'half'),
    ],
  },
]
