-- ============================================================
-- Seed country - ISO 3166-1 alpha-2
-- ============================================================
SET NAMES utf8mb4;

INSERT INTO `country` (`code`, `name_en`, `name_vi`)
VALUES
  ('VN', 'Vietnam',              'Việt Nam'),
  ('CN', 'China',                'Trung Quốc'),
  ('JP', 'Japan',                'Nhật Bản'),
  ('KR', 'South Korea',          'Hàn Quốc'),
  ('SG', 'Singapore',            'Singapore'),
  ('PH', 'Philippines',          'Philippines'),
  ('MY', 'Malaysia',             'Malaysia'),
  ('ID', 'Indonesia',            'Indonesia'),
  ('TH', 'Thailand',             'Thái Lan'),
  ('TW', 'Taiwan',               'Đài Loan'),
  ('HK', 'Hong Kong',            'Hồng Kông'),
  ('IN', 'India',                'Ấn Độ'),
  ('MM', 'Myanmar',              'Myanmar'),
  ('KH', 'Cambodia',             'Campuchia'),
  ('LA', 'Laos',                 'Lào'),
  ('PA', 'Panama',               'Panama'),
  ('LR', 'Liberia',              'Liberia'),
  ('MH', 'Marshall Islands',     'Quần đảo Marshall'),
  ('BS', 'Bahamas',              'Bahamas'),
  ('CY', 'Cyprus',               'Síp'),
  ('MT', 'Malta',                'Malta'),
  ('AG', 'Antigua and Barbuda',  'Antigua và Barbuda'),
  ('KN', 'Saint Kitts and Nevis','Saint Kitts và Nevis'),
  ('VC', 'Saint Vincent and the Grenadines','Saint Vincent và Grenadines'),
  ('GR', 'Greece',               'Hy Lạp'),
  ('NO', 'Norway',               'Na Uy'),
  ('GB', 'United Kingdom',       'Vương quốc Anh'),
  ('DE', 'Germany',              'Đức'),
  ('NL', 'Netherlands',          'Hà Lan'),
  ('FR', 'France',               'Pháp'),
  ('IT', 'Italy',                'Ý'),
  ('DK', 'Denmark',              'Đan Mạch'),
  ('SE', 'Sweden',               'Thụy Điển'),
  ('FI', 'Finland',              'Phần Lan'),
  ('RU', 'Russia',               'Nga'),
  ('US', 'United States',        'Hoa Kỳ'),
  ('AU', 'Australia',            'Úc'),
  ('NZ', 'New Zealand',          'New Zealand'),
  ('AE', 'United Arab Emirates', 'Các Tiểu vương quốc Ả Rập Thống nhất'),
  ('SA', 'Saudi Arabia',         'Ả Rập Xê Út'),
  ('QA', 'Qatar',                'Qatar'),
  ('KW', 'Kuwait',               'Kuwait'),
  ('BH', 'Bahrain',              'Bahrain'),
  ('OM', 'Oman',                 'Oman'),
  ('EG', 'Egypt',                'Ai Cập'),
  ('ZA', 'South Africa',         'Nam Phi'),
  ('BR', 'Brazil',               'Brazil'),
  ('MX', 'Mexico',               'Mexico'),
  ('CA', 'Canada',               'Canada'),
  ('ES', 'Spain',                'Tây Ban Nha'),
  ('PT', 'Portugal',             'Bồ Đào Nha'),
  ('PL', 'Poland',               'Ba Lan'),
  ('HR', 'Croatia',              'Croatia'),
  ('TR', 'Turkey',               'Thổ Nhĩ Kỳ'),
  ('UA', 'Ukraine',              'Ukraine'),
  ('PK', 'Pakistan',             'Pakistan'),
  ('BD', 'Bangladesh',           'Bangladesh'),
  ('LK', 'Sri Lanka',            'Sri Lanka')
ON DUPLICATE KEY UPDATE
  name_en = VALUES(name_en),
  name_vi = VALUES(name_vi);
