-- ============================================================
-- TASK-A1: Thêm cột status, approved_by, approved_at, reject_reason, referred_by_center_id vào training_enrollment
-- Chạy: mysql -u root marineport < backend/migrations/014_enrollment_status_a1.sql
-- ============================================================
-- training_enrollment status/approval fields removed (training_center/course/enrollment disabled)
