-- ============================================================
-- TASK-A2: Bổ sung cột label, max_uses cho qr_enrollment_link (bảng đã có từ 010)
-- Thêm index idx_qr_token, idx_qr_course; cho phép expires_at NULL
-- Chạy: mysql -u root marineport < backend/migrations/015_qr_enrollment_link_a2.sql
-- ============================================================
-- qr_enrollment_link customization removed (training_center/course/enrollment disabled)
