-- ============================================================
-- TASK-A3: Bảng enrollment_waitlist - danh sách chờ khi khóa học đã đầy
-- Chạy: mysql -u root marineport < backend/migrations/016_enrollment_waitlist_a3.sql
-- ============================================================
-- enrollment_waitlist customization removed (training_center/course/enrollment disabled)
