-- 023_certificate_type_cn_report.sql
-- Report mapping status for CN certificate checklist (FOUND/MISSING)

DROP TEMPORARY TABLE IF EXISTS tmp_expected_certificate_alias;
CREATE TEMPORARY TABLE tmp_expected_certificate_alias (
  expected_key VARCHAR(80) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  alias_code VARCHAR(80) NOT NULL,
  PRIMARY KEY (expected_key, alias_code)
);

INSERT INTO tmp_expected_certificate_alias (expected_key, display_name, alias_code) VALUES
  ('PASSPORT', 'PASSPORT', 'PASSPORT'),
  ('SEAMAN_BOOK', 'SEAMANBOOK', 'SEAMAN_BOOK'),
  ('SEAMAN_BOOK', 'SEAMANBOOK', 'SEAMAN-BOOK'),
  ('SEAFARER_ID_CARD', 'S.P.', 'SEAFARER_ID_CARD'),
  ('COC', 'COC', 'COMPETENCY_DECK'),
  ('COC', 'COC', 'COMPETENCY_ENGINE'),
  ('COC', 'COC', 'COMPETENCY_RADIO'),
  ('GMDSS', 'GMDSS', 'GMDSS-GOC'),
  ('GMDSS', 'GMDSS', 'GMDSS-ROC'),
  ('GMDSS', 'GMDSS', 'GOC'),
  ('CERT_PROF_SEAFARERS', 'CERTIFICATE OF PROFICIENCY FOR SEAFARERS', 'CERT_PROF_SEAFARERS'),
  ('BASIC_TRAINING', 'BASIC TRAINING', 'STCW-BASIC'),
  ('BASIC_TRAINING', 'BASIC TRAINING', 'BASIC_TRAINING'),
  ('PSCRB', 'PROFICIENCY IN SURVIVAL CRAFT AND RESCUE BOAT', 'PSCRB'),
  ('AFF', 'TRAINING IN ADVANCED FIRE-FIGHTING', 'AFF'),
  ('MEFA', 'TRAINING IN MEDICAL FIRST AID', 'MEFA'),
  ('MFA', 'TRAINING IN MEDICAL FIRST AID', 'MFA'),
  ('MC', 'TRAINING IN MEDICAL CARE', 'MC'),
  ('SECURITY_AWARENESS', 'SECURITY AWARENESS TRAINING', 'SECURITY-AWARE'),
  ('SECURITY_AWARENESS', 'SECURITY AWARENESS TRAINING', 'SECURITY_AWARENESS'),
  ('SECURITY_DUTIES', 'SEAFARERS WITH DESIGNATED SECURITY DUTIES', 'DESIGNATED-SEC'),
  ('SECURITY_DUTIES', 'SEAFARERS WITH DESIGNATED SECURITY DUTIES', 'SECURITY_DUTIES'),
  ('SSO', 'PROFICIENCY FOR SHIP SECURITY OFFICER', 'SSO'),
  ('MEDICAL_CERT_SEAFARERS', 'MEDICAL CERTIFICATE FOR SEAFARERS', 'MEDICAL-FITNESS'),
  ('MEDICAL_CERT_SEAFARERS', 'MEDICAL CERTIFICATE FOR SEAFARERS', 'MEDICAL_FITNESS'),
  ('CHEMICAL_FAM', 'CHEMICAL TANKER FAMILIARIZATION COURSE', 'TANKER-CHEM-BASIC'),
  ('CHEMICAL_FAM', 'CHEMICAL TANKER FAMILIARIZATION COURSE', 'TANKER_CHEMICAL'),
  ('CHEMICAL_ADV', 'CHEMICAL TANKER ADVANCE OPERATION', 'TANKER-CHEM-ADV'),
  ('OIL_FAM', 'OIL TANKER FAMILIARIZATION COURSE', 'TANKER-OIL-BASIC'),
  ('OIL_FAM', 'OIL TANKER FAMILIARIZATION COURSE', 'TANKER_OIL'),
  ('OIL_ADV', 'OIL TANKER ADVANCE OPERATION', 'TANKER-OIL-ADV'),
  ('INERT_GAS_CRUDE_OIL_WASHING', 'INERT GAS & CRUDE OIL WASHING', 'INERT_GAS_CRUDE_OIL_WASHING'),
  ('RADAR_OBSERVATION', 'RADAR OBSERVATION / SIMULATOR', 'RADAR_OBSERVATION'),
  ('RADAR_OBSERVATION', 'RADAR OBSERVATION / SIMULATOR', 'RADAR-ARPA'),
  ('ELECTRONIC_NAV_AIDS', 'ELECTRONIC NAVIGATIONAL AIDS', 'ELECTRONIC_NAV_AIDS'),
  ('ELECTRONIC_NAV_AIDS', 'ELECTRONIC NAVIGATIONAL AIDS', 'ECDIS'),
  ('ARPA', 'A.R.P.A.', 'ARPA'),
  ('SHIPBOARD_MANAGEMENT', 'SHIPBOARD MANAGEMENT COURSE', 'SHIPBOARD_MANAGEMENT'),
  ('COVID19_VACCINATION', 'COVID-19 VACCINATION CERTIFICATE', 'COVID19_VACCINATION');

SELECT
  t.expected_key,
  t.display_name,
  GROUP_CONCAT(DISTINCT t.alias_code ORDER BY t.alias_code SEPARATOR ', ') AS mapped_alias_codes,
  CASE WHEN COUNT(ct.id) > 0 THEN 'FOUND' ELSE 'MISSING' END AS status,
  GROUP_CONCAT(DISTINCT ct.code ORDER BY ct.code SEPARATOR ', ') AS matched_codes
FROM tmp_expected_certificate_alias t
LEFT JOIN certificate_type ct
  ON ct.code = t.alias_code
GROUP BY t.expected_key, t.display_name
ORDER BY
  CASE WHEN COUNT(ct.id) > 0 THEN 0 ELSE 1 END,
  t.expected_key;
