CREATE TABLE IF NOT EXISTS `salary_deductions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `salary_id` INT NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`salary_id`) REFERENCES `seafarer_salary`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
